### ISSUE TITLE
Allow for longer lists.

### ISSUE THREAD

**Issue by tcoopman** [NoRedInk/elm-check#11]
Is there any reason that the `list` only generates list between 0 and 10?

``` elm
{-| Given a producer of a type, create a producer of a list of that type.
Generates random lists of values of length between 0 and 10.
-}
list : Producer a -> Producer (List a)
list prod =
  Producer
    (Random.List.rangeLengthList 0 10 prod.generator)
    -- TODO possibly have longer lists?
    (Shrink.list prod.shrinker)
```

Can we allow for longer lists, or maybe add a `listBetween` function that takes two ints?
I can create this as a PR if someone is interested.

``` elm
{-| Given a producer of a type, create a producer of a list of that type.
Generates random lists of values of length between min and max.
-}
list : Int -> Int -> Producer a -> Producer (List a)
list min max prod =
  Producer
    (Random.List.rangeLengthList min max prod.generator)
    (Shrink.list prod.shrinker)
```

**Comment by mgold** [comment]
Hmm, not really! Shrinking will find shorter lists, although it will take longer if the list is long to begin with. But if there's some element or subsequence that causes a bug, it's more likely to happen in a long list. Plus some bugs may require a long list to begin with. So it seems reasonable to scrap and redo the generator.

How about:

``` elm
generator =
      Random.Extra.frequency
        [ ( 1, Random.Extra.constant [] )
        , ( 1, Random.map (\x -> [x]) prod.generator )
        , ( 3, ... small list 2-10 items
        , ( 2, ... medium list 10-100 items
        , ( 0.5, ... large list 100-400 items
        ]
```

Seem reasonable? I'm open to suggestions.

**Comment by tcoopman** [comment]
I didn't think about shrinking, it's just my first usage of property based testing. 
I stumbled onto this because elm-check didn't find some bug that I knew was there with longer lists. So with my limited knowledge of elm-check,  the solution you propose looks reasonable to me.

**Comment by mgold** [comment]
Fixed in the elm-community fork. Thanks for reporting!
