### ISSUE TITLE
Elm 0.18 support

### ISSUE THREAD

**Issue by korczis** [NoRedInk/elm-check#14]
Where it is?

**Comment by mgold** [comment]
[Here](https://github.com/elm-community/elm-test#from-1x-and-elm-check). The repo itself moved to elm-community. elm-check syntax is supported through legacy helpers but those will not be ported to 0.19.

See also the top of the README on GitHub (not the package site).

**Comment by dennissivia** [comment]
@mgold I wonder if it is worth adding that Info to the readme. What do you think. I was considering linking to that, but failed searching for an "official" statement in this repo.

**Comment by mgold** [comment]
It *is* in the README. Right at the top. I added "and later" to "0.17" though. Would it help if we released a patch version so it shows up on the package registry? But there the 0.18 packages are separated so it would be hard to come across this one anyway. This package hasn't been current for 15 months. Sheesh.

**Comment by dennissivia** [comment]
Yes you are right. I was thinking about the "use elm-test" statement that the community version has. But I think it's fine already.thanks
