### ISSUE TITLE
No runner included

### ISSUE THREAD

**Issue by halbgut** [NoRedInk/elm-check#2]
You seem to have removed the [runner](https://github.com/TheSeamau5/elm-check/tree/master/src/Check/Runner). Is there a specific reason for that? If so could you update the README on how to run tests in newer versions of the package?

```
Error: -- NAMING ERROR -
[...]
Cannot find variable `display`
23│ main = display result
^^^^^^^
Detected errors in 1 module.
```

**Comment by mgold** [comment]
See [this thread](https://groups.google.com/forum/#!searchin/elm-discuss/runner$20elm-check/elm-discuss/sBqqzHGC2dE/0BFzkiQJDQAJ).

There is also an open PR on this repo to add a display function, but I think the better option is to play nicely with elm-test. Any large enough project is going to have non-property based tests.

Action items:
- [x] Remove inaccurate information from README
- [x] Open a PR to elm-check to make integrating with it easier

**Comment by mgold** [comment]
When deadfoxygrandpa/elm-test#37 is merged, I can add the conversion function to this package and update the docs.

**Comment by mgold** [comment]
The inaccurate README has been fixed.

Use `Check.Test.evidenceToTest` to convert your `Evidence` into a test that `elm-test` can display using its runners. There's no need to duplicate writing the runners here (although the `Evidence` type is exported, so you can inspect it to your heart's content).
