### ISSUE TITLE
Planning deprecations [feedback request]

### ISSUE THREAD

**Issue by mgold** [NoRedInk/elm-check#3]
Once a new version of `elm-test` is published, I'll be able to add much better support for viewing results as described on other issues. I'm also willing to overhaul the README and docs to bring them up to date. As part of this, I'd like to deprecate (in 2.1.0) and remove (in 3.0.0) some of the API (PRs to follow assuming positive response here). The reason I'm opening this issue is to ask, **does anyone actually use any of these?** (I know that this library was forked, so there may be a difference of opinion from the original author.)
- Check.Test - everything. Replace with a function to turn `Evidence` into an `elm-Test` `Test`.
- Check.Investigator
  - Perhaps rename to _Producer_? Seems more intuitive - it's a thing that can produce values.
  - Remove `investigator` in favor of the identical record constructor `Investigator`.
- Check - does anyone use the functions not in the DSL? Namely,
  - `claimTrue`
  - `claimFalse`
  - `claimN`
  - `claimNTrue`
  - `claimNFalse`

My personal opinion on APIs is that they should be minimal. "No one uses these functions, but you'd never know since they're listed first" is something to be avoided. People seem to like the DSL, so I think that's what should be the first thing in the docs and README.

**Comment by rtfeldman** [comment]
I totally :heart_eyes: all of these. Love it!

**Comment by mgold** [comment]
Thanks for the encouragement! You can see the progress on the `breaking` branch. I'm currently waiting on a PR to `elm-test` - not the one mentioned in OP, another one - that will make multiline tests display much better in the browser.

**Comment by mgold** [comment]
Done in 3.0.0.
